version: '3'
services:
  eureka-server:
    image: ms-registry
    ports:
      - 8888:8888

  gateway-service:
     image: gateway
     depends_on:
        - eureka-server
     ports:
       - 7777:7777
     environment:
        profile: "default"
        eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka"  
     restart: on-failure

  ms-formation-service:
     image: ms-formation
     depends_on:
        - eureka-server
        - gateway-service
     ports:
       - 8090:8090
     environment:
        profile: "default"
        eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka"  
     restart: on-failure   

  ms-scolarite-service:
     image: ms-scolarite
     depends_on:
        - eureka-server
        - gateway-service
     ports:
       - 8082:8082
     environment:
        profile: "default"
        eureka.client.serviceUrl.defaultZone: "http://eureka-server:8888/eureka"  
     restart: on-failure     